#!/bin/sh

# Uses django-mailer to periodically send out the scheduled/deferred emails.
# Since this is club-neutral, we use our own minimal settings file.

if [ $# -gt 0 ]; then
  source /home/user/club-websystem/bin/activate
  export DJANGO_SETTINGS_MODULE="system.settings._production_mailer"

  log=$VIRTUAL_ENV/mailer.log
  #(echo; echo; echo -n "$1 - "; date) >> $log
  python $VIRTUAL_ENV/src/manage.py $* >> $log 2>&1
else
  echo "You must specify one parameter: either send_mail or retry_deferred"
fi
