#!/bin/sh

# Runs the development server. Specify the settings file (without the .py extension) as the first
#   parameter. The remaining parameters will be passed directly to manage.py

P="runserver 0.0.0.0:8000"
if [ $# -gt 0 ]; then
  settings=$1
  shift
  if [ $# -gt 0 ]; then
    P="$*"
  fi
else
  settings="dev_infosec"
fi

if [ -f "$VIRTUAL_ENV/src/system/settings/$settings.py" ]; then
  export DJANGO_SETTINGS_MODULE="system.settings.$settings"

  r="$VIRTUAL_ENV/bin/python $VIRTUAL_ENV/src/manage.py $P"
  echo $r
  echo ------------------------------------
  $r
else
  echo "Cannot find settings file named '$settings'"
fi
