#!/bin/sh

# Run the production UWSGI server. Accepts only one parameter -- the settings file (without
#   the .py extension). Will also look for a UWSGI .ini file with the same name

if [ $# -gt 0 ]; then
  settings=$1
else
  settings="_production_infosec"
fi

if [ -f "$VIRTUAL_ENV/src/system/settings/$settings.py" ]; then
  if [ -f "$VIRTUAL_ENV/src/system/settings/$settings.ini" ]; then
    export DJANGO_SETTINGS_MODULE="system.settings.$settings"

    r="uwsgi --ini $VIRTUAL_ENV/src/system/settings/$settings.ini"
    echo $r
    echo ------------------------------------
    $r
  else
    echo "Cannot find UWSGI file named '$settings.ini'"
  fi
else
  echo "Cannot find settings file named '$settings.py'"
fi
